name: Release

on:
  release:
    types: [created]

jobs:
  contract-release:
    name: Contract File Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Optimize Contract
        run: make optimize

      - name: Release Contract Files
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/forward_market_smart_contract.wasm
            artifacts/checksums.txt
